# Generated by Django 5.2.2 on 2025-08-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
