# Generated by Django 5.2.2 on 2025-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_adminuser_phone_alter_coordinator_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='type',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='template_type',
            field=models.CharField(choices=[('offer', 'Internship Offer Letter'), ('completion', 'Internship Completion Certificate')], default='completion', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_backgrounds/'),
        ),
    ]
