# Generated by Django 5.2.3 on 2025-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_certificate_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='signature_image',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='completion_date',
            field=models.DateField(),
        ),
    ]
