# Generated by Django 5.2.3 on 2025-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_coordinator_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Unknown User', max_length=100),
        ),
    ]
