# Generated by Django 5.2.3 on 2025-06-27 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_certificate_issue_date_certificate_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
