# Generated by Django 5.2.2 on 2025-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquery',
            old_name='query_text',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='student',
        ),
        migrations.AddField(
            model_name='studentquery',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='student_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentquery',
            name='student_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
