# Generated by Django 5.2.3 on 2025-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_adminuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('offer', 'Internship Offer Letter'), ('completion', 'Internship Completion Certificate')], max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('title', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('completion_date', models.DateField()),
                ('director_name', models.CharField(default='Surendar S', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
