# Generated by Django 5.2.3 on 2025-06-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_certificate_end_date_certificate_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(),
        ),
    ]
