# Generated by Django 5.2.2 on 2025-09-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_certificate_template_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('offer', 'Internship Offer Letter'), ('completion', 'Internship Completion Certificate')], max_length=20, unique=True)),
                ('selected_template', models.CharField(choices=[('default', 'Default Template'), ('landscape1', 'Landscape Template 1'), ('landscape2', 'Landscape Template 2')], default='default', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='template_choice',
        ),
    ]
