# Generated by Django 5.2.3 on 2025-06-25 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
