# Generated by Django 5.2.3 on 2025-06-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_certificate_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='program',
            new_name='department',
        ),
    ]
