# Generated by Django 5.2.2 on 2025-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_templatesetting_remove_certificate_template_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template_choice',
            field=models.CharField(choices=[('default', 'Default Template'), ('landscape1', 'Landscape Template 1'), ('landscape2', 'Landscape Template 2')], default='default', max_length=20),
        ),
    ]
