# Generated by Django 5.2.2 on 2025-09-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_certificate_template_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquery',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='accounts.certificate'),
        ),
    ]
