# Generated by Django 5.2.3 on 2025-07-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_email'),
    ]

    operations = [
    ]
