# Generated by Django 5.2.2 on 2025-09-18 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentquery_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquery',
            name='certificate_type',
            field=models.CharField(choices=[('offer', 'Internship Offer Letter'), ('completion', 'Completion Certificate')], default='offer', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.certificate'),
        ),
    ]
