# Generated by Django 5.2.3 on 2025-07-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250702_1109'),
        ('accounts', '0010_create_default_users'),
    ]

    operations = [
    ]
