# Generated by Django 5.2.2 on 2025-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentquery_certificate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_set_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=32),
        ),
    ]
