# Generated by Django 5.2.2 on 2025-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_must_set_password_user_password_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
