# Generated by Django 5.2.2 on 2025-09-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_certificate_certificate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.JSONField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
