# Generated by Django 5.2.2 on 2025-09-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_queuedemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueuedEmail',
        ),
    ]
