# Generated by Django 5.2.3 on 2025-07-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_certificate_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
