# Generated by Django 5.2.2 on 2025-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_contactmessage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('offer', 'Internship Offer Letter'), ('completion', 'Internship Completion Certificate')], max_length=20)),
                ('background_image', models.ImageField(upload_to='certificate_templates/')),
                ('font_family', models.CharField(default='Times New Roman', max_length=100)),
                ('html_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
