# Generated by Django 5.0.4 on 2025-07-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_certificatetemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='department',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='employment_id',
            field=models.CharField(default='TEMP123', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
