# Generated by Django 5.2.2 on 2025-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_adminuser_email_remove_adminuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
