# Generated by Django 5.2.2 on 2025-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_certificate_credential_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
