# Generated by Django 5.2.2 on 2025-08-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_certificate_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_code_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
