# Generated by Django 5.2.2 on 2025-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_certificate_qr_code_certificate_qr_code_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='qr_code_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='qr_codes/'),
        ),
    ]
